package com.courtly.coaches.contexts.notifications.domain.model

enum class NotificationType {
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    TRAINING_SESSION_REQUESTED,
    TRAINING_SESSION_ACCEPTED,
    TRAINING_SESSION_REJECTED,
    TRAINING_SESSION_CANCELLED,
    PAYMENT_CONFIRMED,
    REVIEW_ENABLED,
    MATCH_CREATED,
    MATCH_JOINED,
    MATCH_PARTICIPANT_JOINED,
    MATCH_CANCELLED,
    REVIEW_SUBMITTED,
    REVIEW_RECEIVED
}